# Generated by Django 4.0.4 on 2022-04-22 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily_news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='user',
        ),
    ]
